apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: static-persistence-volume-deployment
spec:  
  template:
    metadata:
      labels:
        app: storagedemo
    spec:
      containers:
      - name: storagedemo
        image: stefanofioravanzo/ubuntu-tail
        volumeMounts:
        - name: azurefileshare
          mountPath: /storage       
      volumes:
      - name: azurefileshare
        persistentVolumeClaim:
          claimName: pipelines-persistence-volume-claim 