apiVersion: v1
kind: PersistentVolume
metadata:
  name: pipelines-persistence-volume
  labels: 
    storage: slow
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  storageClassName: azurefilestorage
  azureFile:
    secretName: azurefile-storage-secret
    shareName: pipelines-share
    readOnly: false
