apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipelines-persistence-volume-claim 
spec:
  accessModes:
    - ReadWriteMany  
  resources:
    requests:
      storage: 5Gi
  storageClassName: azurefilestorage